version: '3.8'

services:
  backend:
    build:
      context: ./sports_backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./sports_backend:/app
      # - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/sportsdb
      - JWT_SECRET=your-secret-key
    networks:
      - sports-network
    depends_on:
      - db

  frontend:
    build:
      context: ./sports
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./sports:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000
    networks:
      - sports-network
    depends_on:
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sportsdb
      MYSQL_USER: sportsuser
      MYSQL_PASSWORD: sportspass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sports-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  sports-network:
    driver: bridge 