
// Temple IDs mapping
export const TEMPLE_IDS = {
  BARKUR: 1,
  HALEYANGADI: 2,
  HOSADURGA: 3,
  KALYANPURA: 4,
  KAPU: 5,
  KARKALA: 6,
  KINNIMULKI: 7,
  MANGALORE: 8,
  MANJESHWARA: 9,
  MULKI: 10,
  PADUBIDRI: 11,
  SALIKERI: 12,
  SIDDAKATTE: 13,
  SURATHKAL: 14,
  ULLALA: 15,
  YERMAL: 16
};
